//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDEDPATIENT
    {
        public int ID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string EMAILADDRESS { get; set; }
        public string USERNAME { get; set; }
        public Nullable<int> CONTACT { get; set; }
        public string GENDER { get; set; }
        public string CATEGORY { get; set; }
        public string DATE { get; set; }
        public string DOB { get; set; }
        public string TIME { get; set; }
    }
}
